export const mainNationRegion = [
    {en: 'Afghanistan', zh: '阿富汗'},
    {en: 'Albania', zh: '阿尔巴尼亚'},
    {en: 'Algeria', zh: '阿尔及利亚'},
    {en: 'Andorra', zh: '安道尔'},
    {en: 'Angola', zh: '安哥拉'},
    {en: 'Anguilla', zh: '安圭拉'},
    {en: 'Argentina', zh: '阿根廷'},
    {en: 'Armenia', zh: '亚美尼亚'},
    {en: 'Aruba', zh: '阿鲁巴'},
    {en: 'Australia', zh: '澳大利亚'},
    {en: 'Austria', zh: '奥地利'},
    {en: 'Azerbaijan', zh: '阿塞拜疆'},
    {en: 'Bahamas', zh: '巴哈马'},
    {en: 'Bahrain', zh: '巴林'},
    {en: 'Bangladesh', zh: '孟加拉国'},
    {en: 'Barbados', zh: '巴巴多斯'},
    {en: 'Belarus', zh: '白俄罗斯'},
    {en: 'Belgium', zh: '比利时'},
    {en: 'Belize', zh: '伯利兹'},
    {en: 'Benin', zh: '贝宁'},
    {en: 'Bhutan', zh: '不丹'},
    {en: 'Bolivia', zh: '玻利维亚'},
    {en: 'Bosnia and Herzegovina', zh: '波斯尼亚黑塞哥维那'},
    {en: 'Botswana', zh: '博茨瓦纳'},
    {en: 'Brazil', zh: '巴西'},
    {en: 'Brunei Darussalam', zh: '文莱达鲁萨兰国'},
    {en: 'Bulgaria', zh: '保加利亚'},
    {en: 'Burkina Faso', zh: '布基纳法索'},
    {en: 'Burundi', zh: '蒲隆地'},
    {en: 'Cambodia', zh: '柬埔寨'},
    {en: 'Cameroon', zh: '喀麦隆'},
    {en: 'Canada', zh: '加拿大'},
    {en: 'Cape Verde', zh: '佛得角'},
    {en: 'Cayman Islands', zh: '开曼群岛'},
    {en: 'Central African Republic', zh: '中非共和国'},
    {en: 'Chad', zh: '乍得'},
    {en: 'Chile', zh: '智利'},
    {en: 'China', zh: '中华人民共和国'},
    {en: 'Christmas Island', zh: '圣诞岛'},
    {en: 'Cocos (Keeling) Islands', zh: '科科斯群岛'},
    {en: 'Colombia', zh: '哥伦比亚'},
    {en: 'Comoros', zh: '刚果民主共和国'},
    {en: 'Democratic Republic of the Congo (Kinshasa)', zh: '刚果共和国'},
    {en: 'Cook Islands', zh: '库克群岛'},
    {en: 'Costa Rica', zh: '哥斯达黎加'},
    {en: "Côte D'ivoire (Ivory Coast)", zh: '科特迪瓦'},
    {en: 'Croatia', zh: '克罗地亚'},
    {en: 'Cuba', zh: '古巴'},
    {en: 'Cyprus', zh: '塞浦路斯'},
    {en: 'Czech Republic', zh: '捷克共和国'},
    {en: 'Denmark', zh: '丹麦'},
    {en: 'Djibouti', zh: '吉布提'},
    {en: 'Dominica', zh: '多米尼克'},
    {en: 'Dominican Republic', zh: '多米尼加共和国'},
    {en: 'East Timor (Timor-Leste)', zh: '东帝汶'},
    {en: 'Ecuador', zh: '厄瓜多尔'},
    {en: 'Egypt', zh: '埃及'},
    {en: 'El Salvador', zh: '萨尔瓦多'},
    {en: 'Equatorial Guinea', zh: '赤道几内亚'},
    {en: 'Eritrea', zh: '厄立特里亚'},
    {en: 'Estonia', zh: '爱沙尼亚'},
    {en: 'Ethiopia', zh: '埃塞俄比亚'},
    {en: 'Falkland Islands', zh: '福克兰群岛'},
    {en: 'Faroe Islands', zh: '法罗群岛'},
    {en: 'Fiji', zh: '斐济'},
    {en: 'Finland', zh: '芬兰'},
    {en: 'France', zh: '法国'},
    {en: 'French Guiana', zh: '法屬圭亞那'},
    {en: 'French Polynesia', zh: '法属波利尼西亚'},
    {en: 'French Southern Territories', zh: '法属南方领土'},
    {en: 'Gabon', zh: '加蓬'},
    {en: 'Gambia', zh: '冈比亚'},
    {en: 'Georgia', zh: '格鲁吉亚'},
    {en: 'Germany', zh: '德国'},
    {en: 'Ghana', zh: '加纳'},
    {en: 'Gibraltar', zh: '直布罗陀'},
    {en: 'Greece', zh: '希腊'},
    {en: 'Greenland', zh: '格陵兰'},
    {en: 'Grenada', zh: '格林纳达'},
    {en: 'Guatemala', zh: '危地马拉瓜地馬拉'},
    {en: 'Guinea', zh: '几内亚'},
    {en: 'Guinea-Bissau', zh: '几内亚比索'},
    {en: 'Guyana', zh: '圭亚那'},
    {en: 'Haiti', zh: '海地'},
    {en: 'Honduras', zh: '洪都拉斯'},
    {en: 'Hong Kong, China', zh: '香港特别行政区'},
    {en: 'Hungary', zh: '匈牙利'},
    {en: 'Iceland', zh: '冰岛'},
    {en: 'India', zh: '印度'},
    {en: 'Indonesia', zh: '印度尼西亚印尼'},
    {en: 'Iran (Islamic Republic of)', zh: '伊朗'},
    {en: 'Iraq', zh: '伊拉克'},
    {en: 'Ireland', zh: '爱尔兰'},
    {en: 'Israel', zh: '以色列'},
    {en: 'Italy', zh: '意大利'},
    {en: 'Ivory Coast', zh: '科特迪瓦'},
    {en: 'Jamaica', zh: '牙买加'},
    {en: 'Japan', zh: '日本'},
    {en: 'Jordan', zh: '约旦'},
    {en: 'Kazakhstan', zh: '哈萨克斯坦'},
    {en: 'Kenya', zh: '肯尼亚'},
    {en: 'Kiribati', zh: '基里巴斯'},
    {en: "Korea, Democratic People's Rep. (North Korea)", zh: '朝鲜'},
    {en: 'Korea, Republic of (South Korea)', zh: '韩国'},
    {en: 'Kosovo', zh: '科索沃'},
    {en: 'Kuwait', zh: '科威特'},
    {en: 'Kyrgyzstan', zh: '吉尔吉斯斯坦'},
    {en: "Lao, People's Democratic Republic", zh: '老挝'},
    {en: 'Latvia', zh: '拉脱维亚'},
    {en: 'Lebanon', zh: '黎巴嫩'},
    {en: 'Lesotho', zh: '莱索托'},
    {en: 'Liberia', zh: '利比里亚'},
    {en: 'Libya', zh: '利比亚'},
    {en: 'Liechtenstein', zh: '列支敦士登'},
    {en: 'Lithuania', zh: '立陶宛'},
    {en: 'Luxembourg', zh: '卢森堡'},
    {en: 'Macau, China', zh: '澳门特别行政区'},
    {en: 'Macedonia, Rep. of', zh: '马其顿'},
    {en: 'Madagascar', zh: '马达加斯加'},
    {en: 'Malawi', zh: '马拉维'},
    {en: 'Malaysia', zh: '马来西亚'},
    {en: 'Maldives', zh: '马尔代夫'},
    {en: 'Mali', zh: '马里'},
    {en: 'Malta', zh: '马耳他'},
    {en: 'Marshall Islands', zh: '马绍尔群岛'},
    {en: 'Martinique', zh: '马提尼克'},
    {en: 'Mauritania', zh: '毛里塔尼亚'},
    {en: 'Mauritius', zh: '毛里求斯'},
    {en: 'Mayotte', zh: '马约特'},
    {en: 'Mexico', zh: '墨西哥'},
    {en: 'Micronesia, Federal States of', zh: '密克罗尼西亚'},
    {en: 'Moldova, Republic of', zh: '摩尔多瓦'},
    {en: 'Monaco', zh: '摩纳哥'},
    {en: 'Mongolia', zh: '蒙古'},
    {en: 'Montenegro', zh: '黑山'},
    {en: 'Montserrat', zh: '蒙塞拉特'},
    {en: 'Morocco', zh: '摩洛哥'},
    {en: 'Mozambique', zh: '莫桑比克'},
    {en: 'Myanmar, Burma', zh: '缅甸'},
    {en: 'Namibia', zh: '纳米比亚'},
    {en: 'Nauru', zh: '瑙鲁'},
    {en: 'Nepal', zh: '尼泊尔'},
    {en: 'Netherlands', zh: '荷兰'},
    {en: 'Netherlands Antilles', zh: '荷属安的列斯群岛'},
    {en: 'New Caledonia', zh: '新喀里多尼亚'},
    {en: 'New Zealand', zh: '新西兰'},
    {en: 'Nicaragua', zh: '尼加拉瓜'},
    {en: 'Niger', zh: '尼日尔'},
    {en: 'Nigeria', zh: '尼日利亚'},
    {en: 'Niue', zh: '纽埃'},
    {en: 'Northern Mariana Islands', zh: '北马里亚纳群岛'},
    {en: 'Norway', zh: '挪威'},
    {en: 'Oman', zh: '阿曼'},
    {en: 'Pakistan', zh: '巴基斯坦'},
    {en: 'Palau', zh: '帕劳'},
    {en: 'Palestinian territories', zh: '巴勒斯坦'},
    {en: 'Panama', zh: '巴拿马'},
    {en: 'Papua New Guinea', zh: '巴布亚新几内亚'},
    {en: 'Paraguay', zh: '巴拉圭'},
    {en: 'Peru', zh: '秘鲁'},
    {en: 'Philippines', zh: '菲律宾'},
    {en: 'Pitcairn Island', zh: '皮特凯恩群岛'},
    {en: 'Poland', zh: '波兰'},
    {en: 'Portugal', zh: '葡萄牙'},
    {en: 'Puerto Rico', zh: '波多黎各'},
    {en: 'Qatar', zh: '卡塔尔'},
    {en: 'Reunion Island', zh: '留尼汪'},
    {en: 'Romania', zh: '罗马尼亚'},
    {en: 'Russian Federation', zh: '俄罗斯'},
    {en: 'Rwanda', zh: '卢旺达'},
    {en: 'Saint Kitts and Nevis', zh: '圣基茨和尼维斯'},
    {en: 'Saint Lucia', zh: '圣卢西亚'},
    {en: 'Saint Vincent and the Grenadines', zh: '圣文森特和格林纳丁斯'},
    {en: 'Samoa', zh: '萨摩亚'},
    {en: 'San Marino', zh: '圣马力诺'},
    {en: 'Sao Tome and Principe', zh: '圣多美普林西比'},
    {en: 'Saudi Arabia', zh: '沙特阿拉伯'},
    {en: 'Senegal', zh: '塞内加尔'},
    {en: 'Serbia', zh: '塞尔维亚'},
    {en: 'Seychelles', zh: '塞舌尔'},
    {en: 'Sierra Leone', zh: '塞拉利昂'},
    {en: 'Singapore', zh: '新加坡'},
    {en: 'Slovakia (Slovak Republic)', zh: '斯洛伐克'},
    {en: 'Slovenia', zh: '斯洛文尼亚'},
    {en: 'Solomon Islands', zh: '所罗门群岛'},
    {en: 'Somalia', zh: '索马里'},
    {en: 'South Africa', zh: '南非'},
    {en: 'South Sudan', zh: '南苏丹'},
    {en: 'Spain', zh: '西班牙'},
    {en: 'Sri Lanka', zh: '斯里兰卡'},
    {en: 'Sudan', zh: '苏丹'},
    {en: 'Suriname', zh: '苏里南'},
    {en: 'Swaziland', zh: '史瓦济兰'},
    {en: 'Sweden', zh: '瑞典'},
    {en: 'Switzerland', zh: '瑞士'},
    {en: 'Syria, Syrian Arab Republic', zh: '叙利亚'},
    {en: 'Taiwan (Republic of China)', zh: '中国台湾省'},
    {en: 'Tajikistan', zh: '塔吉克斯坦'},
    {en: 'Tanzania', zh: '坦桑尼亚'},
    {en: 'Thailand', zh: '泰国'},
    {en: 'Togo', zh: '多哥'},
    {en: 'Tonga', zh: '汤加'},
    {en: 'Trinidad and Tobago', zh: '特立尼达和多巴哥'},
    {en: 'Tunisia', zh: '突尼斯'},
    {en: 'Turkey', zh: '土耳其'},
    {en: 'Turkmenistan', zh: '土库曼斯坦'},
    {en: 'Tuvalu', zh: '吐瓦鲁'},
    {en: 'Uganda', zh: '乌干达'},
    {en: 'Ukraine', zh: '乌克兰'},
    {en: 'United Arab Emirates', zh: '阿拉伯联合酋长国'},
    {en: 'United Kingdom', zh: '联合王国'},
    {en: 'United States', zh: '美国'},
    {en: 'Uruguay', zh: '乌拉圭'},
    {en: 'Uzbekistan', zh: '乌兹别克斯坦'},
    {en: 'Vatican City State (Holy See)', zh: '梵帝冈'},
    {en: 'Venezuela', zh: '委内瑞拉'},
    {en: 'Vietnam', zh: '越南'},
    {en: 'Yemen', zh: '也门'},
    {en: 'Zambia', zh: '赞比亚'},
    {en: 'Zimbabwe', zh: '津巴布韦'}
];

export const mainNationRegionEn = ['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
    'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
    'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
    'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
    'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island', 'Cocos (Keeling) Islands',
    'Colombia', 'Comoros', 'Democratic Republic of the Congo (Kinshasa)', 'Cook Islands', 'Costa Rica',
    "Côte D'ivoire (Ivory Coast)", 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica',
    'Dominican Republic', 'East Timor (Timor-Leste)', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
    'Estonia', 'Ethiopia', 'Falkland Islands', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia',
    'French Southern Territories', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
    'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India', 'Indonesia',
    'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Ivory Coast', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya',
    'Kiribati', "Korea, Democratic People's Rep. (North Korea)", 'Korea, Republic of (South Korea)', 'Kosovo', 'Kuwait', 'Kyrgyzstan',
    "Lao, People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
    'Macau, China', 'Macedonia, Rep. of', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique',
    'Mauritania', 'Mauritius', 'Mayotte', 'Mexico', 'Micronesia, Federal States of', 'Moldova, Republic of', 'Monaco', 'Mongolia', 'Montenegro',
    'Montserrat', 'Morocco', 'Mozambique', 'Myanmar, Burma', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles', 'New Caledonia',
    'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestinian territories',
    'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn Island', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Reunion Island', 'Romania',
    'Russian Federation', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe',
    'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia (Slovak Republic)', 'Slovenia', 'Solomon Islands', 'Somalia',
    'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syria, Syrian Arab Republic',
    'Taiwan (Republic of China)', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste (East Timor)', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago',
    'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
    'United States', 'Uruguay', 'Uzbekistan', 'Vatican City State (Holy See)', 'Venezuela', 'Vietnam', 'Wallis and Futuna Islands', 'Yemen', 'Zambia', 'Zimbabwe'];
